//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamInfo()
        {
            this.ResultInfoes = new HashSet<ResultInfo>();
        }
    
        public int SubjectCode { get; set; }
        public string SubjectName { get; set; }
        public System.DateTime Examdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultInfo> ResultInfoes { get; set; }
    }
}
