//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultInfo
    {
        public int Id { get; set; }
        public int StudentRegNo { get; set; }
        public int SubjectCode { get; set; }
        public double Marks { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
        public virtual ExamInfo ExamInfo { get; set; }
    }
}
