//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testStates.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class user
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string States { get; set; }
        public states states { get; set; }
    }
    public enum states
    {
        india,
        AndhraPradesh,
        maharastra
    }
}
